'use client';

import React, { useState, useEffect, useRef } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import {
  ArrowLeft, FileText, Image, Upload, Download, Edit2,
  CheckCircle, ChevronDown, Loader2, Video, RefreshCw,
} from 'lucide-react';
import { getParentById, relativeTime, type PhotoTag, type AiDraftTone } from '@/data/child-dashboard-mock';

const TONE_LABELS: Record<AiDraftTone, string> = {
  traditional: 'Traditional',
  warm_personal: 'Warm & Personal',
  newspaper: 'Newspaper Notice',
};

const PHOTO_LABELS: Record<PhotoTag, string> = {
  obituary: 'Obituary photo',
  funeral_program: 'Funeral program photo',
};

type TabId = 'parent' | 'ai' | 'kid';

export default function ObituaryPage() {
  const { parentId } = useParams<{ parentId: string }>();
  const rel = getParentById(parentId);

  // Obituary state (mutable local copies of mock data)
  const [aiDraftContent, setAiDraftContent] = useState(rel?.obituary.aiDraftContent || null);
  const [aiDraftTone, setAiDraftTone] = useState<AiDraftTone | null>(rel?.obituary.aiDraftTone || null);
  const [aiDraftGeneratedAt, setAiDraftGeneratedAt] = useState(rel?.obituary.aiDraftGeneratedAt || null);
  const [kidVersionContent, setKidVersionContent] = useState(rel?.obituary.kidVersionContent || '');
  const [kidVersionUpdatedAt, setKidVersionUpdatedAt] = useState(rel?.obituary.kidVersionUpdatedAt || null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [showToneMenu, setShowToneMenu] = useState(false);
  const toneMenuRef = useRef<HTMLDivElement>(null);

  // Determine which tabs are available
  const hasParentWritten = !!rel?.obituary.parentWrittenContent;
  const hasAiDraft = !!aiDraftContent;
  const hasKidVersion = !!kidVersionContent.trim();

  // Default tab logic
  const getDefaultTab = (): TabId => {
    if (hasParentWritten) return 'parent';
    if (hasAiDraft) return 'ai';
    return 'kid';
  };
  const [activeTab, setActiveTab] = useState<TabId>(getDefaultTab());

  // Close tone menu on outside click
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (toneMenuRef.current && !toneMenuRef.current.contains(e.target as Node)) setShowToneMenu(false);
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  // Autosave kid version (debounced)
  const saveTimerRef = useRef<NodeJS.Timeout | null>(null);
  useEffect(() => {
    if (!kidVersionContent.trim()) return;
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current);
    saveTimerRef.current = setTimeout(() => {
      setKidVersionUpdatedAt(new Date().toISOString());
      // TODO: POST to /api/obituary/kid-version when real API exists
      console.log(`TODO: AUTOSAVE_KID_VERSION for ${parentId}`);
    }, 1500);
    return () => { if (saveTimerRef.current) clearTimeout(saveTimerRef.current); };
  }, [kidVersionContent, parentId]);

  if (!rel) {
    return (
      <div className="max-w-3xl mx-auto px-6 py-10 font-inter text-navy">
        <p className="text-zinc-500">Parent not found.</p>
        <Link href="/dashboard/child/overview" className="text-primary font-bold text-sm mt-4 inline-block">Back to dashboard</Link>
      </div>
    );
  }

  const name = rel.parentFirstName;
  const obit = rel.obituary;
  const photoTags: PhotoTag[] = ['obituary', 'funeral_program'];
  const uploadedTags = new Set(obit.photos.map(p => p.tag));

  const handleRegenerate = async (tone: AiDraftTone) => {
    setShowToneMenu(false);
    setIsGenerating(true);
    try {
      // TODO: POST to /api/obituary/generate when real AI exists
      console.log(`TODO: REGENERATE_OBITUARY tone=${tone} for ${parentId}`);
      await new Promise(r => setTimeout(r, 2000)); // Simulate generation delay

      const placeholder = `[AI-generated ${TONE_LABELS[tone]} obituary draft — placeholder]\n\nThis draft would be generated by Claude using ${name}'s recorded stories, personal details, and wishes. The ${TONE_LABELS[tone].toLowerCase()} tone was selected.\n\nIn production, this would be a real, contextual obituary draft that the family member can then edit, copy, or export.`;

      setAiDraftContent(placeholder);
      setAiDraftTone(tone);
      setAiDraftGeneratedAt(new Date().toISOString());
      if (activeTab !== 'ai') setActiveTab('ai');
    } catch (err) {
      console.error('Generation failed:', err);
      alert('Could not generate obituary. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleUseThisVersion = () => {
    if (!aiDraftContent) return;
    setKidVersionContent(aiDraftContent);
    setKidVersionUpdatedAt(new Date().toISOString());
    setActiveTab('kid');
    // TODO: POST to /api/obituary/kid-version when real API exists
    console.log(`TODO: COPY_AI_TO_KID_VERSION for ${parentId}`);
  };

  // Build visible tabs
  const tabs: { id: TabId; label: string; subLabel: string }[] = [];
  if (hasParentWritten) {
    tabs.push({ id: 'parent', label: `${name}'s words`, subLabel: `Written by ${name}` });
  }
  if (hasAiDraft || hasParentWritten) {
    // AI tab available if draft exists OR if parent has content (enough story data assumed)
    tabs.push({ id: 'ai', label: 'AI draft', subLabel: `Generated from ${name}'s stories` });
  }
  // Kid version tab — always show once they've edited, or as the default writing space
  tabs.push({ id: 'kid', label: 'Your version', subLabel: kidVersionUpdatedAt ? `Last edited by you, ${relativeTime(kidVersionUpdatedAt)}` : 'Not started yet' });

  // If no parent written and no AI draft, the only tab is "Your version"
  // But we also want to offer AI generation even without existing draft
  if (!hasParentWritten && !hasAiDraft) {
    tabs.unshift({ id: 'ai', label: 'AI draft', subLabel: 'Generate from available stories' });
  }

  return (
    <div className="max-w-3xl mx-auto px-6 py-10 space-y-8 font-inter text-navy">
      {/* Header */}
      <div className="space-y-4">
        <Link href="/dashboard/child/overview" className="inline-flex items-center gap-2 text-sm text-zinc-400 hover:text-navy font-medium transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to dashboard
        </Link>
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-gold/10 rounded-xl flex items-center justify-center">
            <FileText className="w-5 h-5 text-gold" />
          </div>
          <h1 className="font-playfair text-3xl font-black">{name}&apos;s Obituary & Memorial</h1>
        </div>
      </div>

      {/* Obituary Card with Tabs */}
      <section className="bg-white rounded-3xl border border-zinc-100 shadow-sm">
        {/* Tab Bar */}
        <div className="border-b border-zinc-100 px-8 pt-6">
          <div className="flex gap-1">
            {tabs.map(tab => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`px-5 py-3 text-sm font-bold rounded-t-xl transition-colors border-b-2 -mb-px ${
                  activeTab === tab.id
                    ? 'text-navy border-navy bg-zinc-50/50'
                    : 'text-zinc-400 border-transparent hover:text-zinc-600'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </div>

        {/* Tab Content */}
        <div className="p-8">
          {/* Sub-label for active tab */}
          {tabs.find(t => t.id === activeTab) && (
            <p className="text-xs text-zinc-400 mb-6">
              {tabs.find(t => t.id === activeTab)!.subLabel}
            </p>
          )}

          {/* Parent's Words Tab */}
          {activeTab === 'parent' && hasParentWritten && (
            <div className="space-y-4">
              <div className="bg-zinc-50 rounded-2xl p-6">
                <p className="text-sm text-navy leading-relaxed whitespace-pre-line">{obit.parentWrittenContent}</p>
              </div>
              <button
                onClick={() => {
                  // TODO: Export parent's obituary when real export exists
                  console.log(`TODO: EXPORT_PARENT_OBITUARY for ${parentId}`);
                }}
                className="inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline"
              >
                <Edit2 className="w-4 h-4" /> Edit & export
              </button>
            </div>
          )}

          {/* AI Draft Tab */}
          {activeTab === 'ai' && (
            <div className="space-y-6">
              {aiDraftContent ? (
                <>
                  {/* Tone + timestamp header */}
                  <div className="flex items-center gap-2 text-xs text-zinc-400">
                    <span>AI draft</span>
                    <span>&middot;</span>
                    <span className="font-medium text-zinc-500">{aiDraftTone ? TONE_LABELS[aiDraftTone] : 'Unknown tone'}</span>
                    {aiDraftGeneratedAt && (
                      <>
                        <span>&middot;</span>
                        <span>Generated {relativeTime(aiDraftGeneratedAt)}</span>
                      </>
                    )}
                  </div>

                  {/* Draft text (read-only) */}
                  <div className="bg-zinc-50 rounded-2xl p-6">
                    <p className="text-sm text-navy leading-relaxed whitespace-pre-line">{aiDraftContent}</p>
                  </div>

                  {/* Action buttons */}
                  <div className="flex items-center gap-3">
                    {/* Regenerate dropdown */}
                    <div className="relative" ref={toneMenuRef}>
                      <button
                        onClick={() => setShowToneMenu(!showToneMenu)}
                        disabled={isGenerating}
                        className="inline-flex items-center gap-2 text-sm font-bold text-zinc-500 bg-zinc-100 px-5 py-2.5 rounded-xl hover:bg-zinc-200 transition-colors disabled:opacity-40"
                      >
                        {isGenerating ? <Loader2 size={14} className="animate-spin" /> : <RefreshCw size={14} />}
                        Regenerate
                        <ChevronDown size={14} />
                      </button>
                      {showToneMenu && (
                        <div className="absolute top-full left-0 mt-2 bg-white rounded-xl border border-zinc-100 shadow-xl z-20 w-56 py-1 animate-in fade-in slide-in-from-top-2 duration-200">
                          {(Object.entries(TONE_LABELS) as [AiDraftTone, string][]).map(([tone, label]) => (
                            <button
                              key={tone}
                              onClick={() => handleRegenerate(tone)}
                              className="w-full text-left px-4 py-3 text-sm hover:bg-zinc-50 transition-colors flex items-center justify-between"
                            >
                              <span className="font-medium text-navy">{label}</span>
                              {aiDraftTone === tone && <CheckCircle size={14} className="text-primary" />}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>

                    {/* Use this version */}
                    <button
                      onClick={handleUseThisVersion}
                      disabled={isGenerating}
                      className="inline-flex items-center gap-2 text-sm font-bold text-white bg-navy px-5 py-2.5 rounded-xl hover:bg-navy/90 transition-colors disabled:opacity-40"
                    >
                      Use this version
                    </button>
                  </div>
                </>
              ) : (
                /* No AI draft yet — offer generation */
                <div className="text-center py-8 space-y-4">
                  <p className="text-sm text-zinc-500">
                    No AI draft has been generated yet. Choose a tone to create one from {name}&apos;s stories.
                  </p>
                  <div className="flex justify-center gap-3">
                    {(Object.entries(TONE_LABELS) as [AiDraftTone, string][]).map(([tone, label]) => (
                      <button
                        key={tone}
                        onClick={() => handleRegenerate(tone)}
                        disabled={isGenerating}
                        className="text-sm font-bold text-navy bg-zinc-100 px-5 py-2.5 rounded-xl hover:bg-zinc-200 transition-colors disabled:opacity-40"
                      >
                        {isGenerating ? <Loader2 size={14} className="animate-spin inline mr-1" /> : null}
                        {label}
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Your Version Tab */}
          {activeTab === 'kid' && (
            <div className="space-y-4">
              <textarea
                value={kidVersionContent}
                onChange={e => setKidVersionContent(e.target.value)}
                placeholder={`Write your version of ${name}'s obituary here...`}
                rows={12}
                className="w-full bg-zinc-50 border-2 border-zinc-100 rounded-2xl px-5 py-4 text-navy outline-none focus:border-primary/30 transition-all resize-none text-sm leading-relaxed"
              />
              {kidVersionUpdatedAt && (
                <p className="text-xs text-zinc-400 flex items-center gap-1.5">
                  <CheckCircle size={12} className="text-primary" /> Saved {relativeTime(kidVersionUpdatedAt)}
                </p>
              )}
              <button
                onClick={() => {
                  // TODO: Export kid's version when real export exists
                  console.log(`TODO: EXPORT_KID_OBITUARY for ${parentId}`);
                }}
                disabled={!kidVersionContent.trim()}
                className="inline-flex items-center gap-2 text-sm font-bold text-primary hover:underline disabled:opacity-30 disabled:no-underline"
              >
                <Edit2 className="w-4 h-4" /> Edit & export
              </button>
            </div>
          )}
        </div>
      </section>

      {/* Photos + Memorial Video */}
      <section className="bg-white rounded-3xl border border-zinc-100 shadow-sm p-8 space-y-6">
        <div className="flex items-center gap-3">
          <Image className="w-5 h-5 text-gold" />
          <h2 className="font-bold text-navy text-lg">Photos & Video</h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Photo tiles — obituary + funeral program only */}
          {photoTags.map(tag => {
            const isUploaded = uploadedTags.has(tag);
            return (
              <div key={tag} className="border border-zinc-100 rounded-2xl overflow-hidden">
                <div className={`aspect-[4/3] flex items-center justify-center ${isUploaded ? 'bg-zinc-100' : 'bg-zinc-50'}`}>
                  {isUploaded ? (
                    <div className="text-center space-y-2">
                      <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center mx-auto">
                        <CheckCircle className="w-6 h-6 text-primary" />
                      </div>
                      <p className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">Photo uploaded</p>
                    </div>
                  ) : (
                    <div className="text-center space-y-2">
                      <div className="w-12 h-12 bg-zinc-100 rounded-full flex items-center justify-center mx-auto">
                        <Image className="w-6 h-6 text-zinc-300" />
                      </div>
                      <p className="text-[10px] font-bold uppercase tracking-widest text-zinc-300">No photo</p>
                    </div>
                  )}
                </div>
                <div className="p-4 space-y-3">
                  <p className="text-xs font-bold text-navy">{PHOTO_LABELS[tag]}</p>
                  {isUploaded ? (
                    <p className="text-[10px] text-zinc-400">Chosen by {name}</p>
                  ) : (
                    <div className="space-y-2">
                      <p className="text-[10px] text-zinc-400">{name} didn&apos;t choose one — you can add one here</p>
                      <button
                        onClick={() => {
                          // TODO: Open file picker when real upload exists
                          console.log(`TODO: UPLOAD_PHOTO tag=${tag} for ${parentId}`);
                        }}
                        className="inline-flex items-center gap-1.5 text-xs font-bold text-primary hover:underline"
                      >
                        <Upload className="w-3 h-3" /> Upload
                      </button>
                    </div>
                  )}
                </div>
              </div>
            );
          })}

          {/* Memorial Video status tile */}
          <div className="border border-zinc-100 rounded-2xl overflow-hidden">
            <div className="aspect-[4/3] flex items-center justify-center bg-zinc-50">
              <div className="text-center space-y-2">
                <div className={`w-12 h-12 rounded-full flex items-center justify-center mx-auto ${obit.hasMemorialVideo ? 'bg-primary/10' : 'bg-zinc-100'}`}>
                  <Video className={`w-6 h-6 ${obit.hasMemorialVideo ? 'text-primary' : 'text-zinc-300'}`} />
                </div>
                {obit.hasMemorialVideo ? (
                  <p className="text-[10px] font-bold uppercase tracking-widest text-primary">Uploaded</p>
                ) : (
                  <p className="text-[10px] font-bold uppercase tracking-widest text-zinc-300">Not uploaded</p>
                )}
              </div>
            </div>
            <div className="p-4 space-y-1">
              <p className="text-xs font-bold text-navy">Memorial Video</p>
              {obit.hasMemorialVideo ? (
                <p className="text-[10px] text-zinc-400">{name} uploaded a video. Available after release.</p>
              ) : (
                <p className="text-[10px] text-zinc-400">Not uploaded</p>
              )}
            </div>
          </div>
        </div>
      </section>

      {/* Export */}
      <section className="bg-white rounded-3xl border border-zinc-100 shadow-sm p-8 space-y-4">
        <h2 className="font-bold text-navy text-lg">Export</h2>
        <p className="text-sm text-zinc-500 leading-relaxed">
          Includes the currently selected obituary text, all photos, and any AI-generated alternatives.
        </p>
        <button
          onClick={() => {
            // TODO: Generate and download ZIP when real export exists
            console.log(`TODO: DOWNLOAD_ZIP for ${parentId}, active tab: ${activeTab}`);
          }}
          className="inline-flex items-center gap-2 bg-navy text-white font-bold text-sm px-6 py-3 rounded-xl hover:bg-navy/90 transition-colors"
        >
          <Download className="w-4 h-4" /> Download everything as zip
        </button>
      </section>
    </div>
  );
}
